interlock:
    image: ehazlett/interlock:1.1.0
    command: -D run
    tty: true
    ports:
        - 5000
    environment:
        INTERLOCK_CONFIG: |
            ListenAddr = ":5000"
            DockerURL = "${SWARM_HOST}"
            TLSCACert = "/var/lib/boot2docker/ca.pem"
            TLSCert = "/var/lib/boot2docker/cert.pem"
            TLSKey = "/var/lib/boot2docker/key.pem"
            
            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/nginx/nginx.conf"
            PidPath = "/etc/nginx/nginx.pid"
            MaxConn = 1024
            Port = 80
    volumes:
        - /Users/titan/.docker/machine/certs:/var/lib/boot2docker:ro

web:
  restart: always
  image: titanlien/flask_web
  ports:
    - "5000"
  links: 
    - mysql:mysql
  volumes:
    - /app/static
  labels:
    - "interlock.hostname=test"
    - "interlock.domain=local"

nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
        - 80:80
        - 443:443
    labels:
        - "interlock.ext.name=nginx"

mysql:
  image: mysql:5.7.10
  environment:
    - MYSQL_ROOT_PASSWORD=sql
    - MYSQL_DATABASE=BucketList
  volumes:
    - ./mysql:/docker-entrypoint-initdb.d
  volumes_from: 
    - dbstore
  expose:
    - "3306"

dbstore:
  image: busybox
  volumes:
    - /var/lib/mysql 
