web:
  restart: always
  image: titanlien/flask_web
  expose:
    - "5000"
  links: 
    - mysql:mysql
  volumes:
    - /app/static

nginx:
  restart: always
  image: titanlien/flask_nginx
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - web
  links:
    - web:web

mysql:
  image: mysql:5.7.10
  environment:
    - MYSQL_ROOT_PASSWORD=sql
    - MYSQL_DATABASE=BucketList
  volumes:
    - ./mysql:/docker-entrypoint-initdb.d
  volumes_from: 
    - dbstore
  expose:
    - "3306"

dbstore:
  image: busybox
  volumes:
    - /var/lib/mysql 
